# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: aartipanchal539@gmail.com
author_name: AARTI
contract_name: verified_protocol
deployment_language: python
preset_name: production
project_name: verified_protocol

